# Generated by Django 2.0.5 on 2018-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_app', '0002_auto_20180521_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='total_spend',
        ),
        migrations.AddField(
            model_name='address',
            name='total_sent',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='final_balance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='total_received',
            field=models.BigIntegerField(),
        ),
    ]
