# Generated by Django 2.0.5 on 2018-05-21 13:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_app', '0003_auto_20180521_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='inputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
