# Generated by Django 2.0.5 on 2018-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_app', '0004_auto_20180521_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='inputs',
            field=models.TextField(),
        ),
    ]
