# Generated by Django 2.0.5 on 2018-05-21 16:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bc_app', '0005_auto_20180521_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='inputs',
            field=jsonfield.fields.JSONField(),
        ),
    ]
