# Generated by Django 2.0.5 on 2018-05-22 08:58

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_app', '0009_auto_20180522_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='outputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), size=None),
        ),
    ]
